DjangoBlog/Blog/urls.py
from django.contrib import admin
from django.urls import path

from Blog import views

urlpatterns = [
    path('', views.index ),
    path('tag/<slug:tag_slug>/', views.index, name='post_list_by_tag_name' ),
    path('<int:id>/share', views.MailSendView),
    path('<int:year>/<int:month>/<int:day>/<slug:post>', views.post_detail_view,name = 'post_detail' ),
]

DjangoBlog/DjangoBlog/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

DjangoBlog/Blog/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager

from django.urls import reverse

from django.utils import timezone
# Create your models here.

class CustomManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (('draft','Draft') , ('published','Published'))
    title = models.CharField(max_length=256)
    slug = models.SlugField(max_length=264, unique_for_date='publish')
    author = models.ForeignKey(User, related_name='blog_posts', on_delete=models.CASCADE)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now ) 
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    objects = CustomManager()
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("post_detail", kwargs={'year':self.publish.year,'month':int(self.publish.strftime('%m')),\
            'day':int(self.publish.strftime('%d')),'post':self.slug })

class Comment(models.Model):
    post = models.ForeignKey(Post ,related_name = 'comments', on_delete=models.CASCADE)
    name = models.CharField(max_length = 50)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ('-created',)
        
    def __str__(self):
        return f"Commented By {self.name} on {self.created}"
    
    
# ----------------------Dropdown Choice Field 
# CHOICES = (('a','A') , ('b','B'))
# in this Ex A and B is shown to end User BUT a and b are stored in the backend database 
# used as
# COUNTRY =  (('in','India') , ('us','United States'))
# in model class use as 
# country = models.CharField(max_length=10 , choices=COUNTRY , default='in')

# -----------------------Slug Field 
# used for seo purpose, to build proper human understandable urls 
# slug = models.SlugField(max_length=256 , unique_for_date='published')
# unique_for_date means unique slug per published date 
# i.e there will be one and only unique slug on a particular date no duplicate slug on a same day 

# primary key --> id(default) 

# Foreign Key --> 
# class Posts(models.Model):
#     author = models.ForeignKey(User , related_name='blog_posts')
    
# Field author is many-to-one mapping with respect to model post 
# many-to-one mapping is established by using models.ForeignKey() method 

# DateTime Field 
# from django.utils import timezone
# publishes_Date = models.DateTimeField(default=timezone.now )
# auto_now = True use whenever we use post.save() method that date and time will be saved in database by default 

DjangoBlog/Blog/forms.py
from django import forms 

from Blog.models import *

class EmailSendForm(forms.Form):
    name = forms.CharField(widget=forms.Textarea(attrs={'rows':1,'class':'ml-2 text-danger rounded font-weight-bold width-100'}))
    email = forms.EmailField(widget=forms.Textarea(attrs={'rows':1,'class':'ml-2 text-danger rounded font-weight-bold width-100'}))
    to = forms.CharField(widget=forms.Textarea(attrs={'rows':1,'class':'ml-2 text-danger rounded font-weight-bold width-100'}))
    comments = forms.CharField(required=False, widget=forms.Textarea(attrs={'rows':6,'class':'ml-2 text-danger rounded font-weight-bold width-100'}))
    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','email','body')
        widgets = {
            'body':forms.Textarea(attrs={'rows':6,'class':'ml-2 text-danger rounded font-weight-bold width-100'}),
            'name':forms.Textarea(attrs={'rows':1,'class':'ml-2 text-danger rounded font-weight-bold width-100'}),
            'email':forms.Textarea(attrs={'rows':1,'class':'ml-2 text-danger rounded font-weight-bold width-100'}),
        }

DjangoBlog/Blog/views.py
from django.shortcuts import render , get_object_or_404

from django.core.paginator import Paginator , PageNotAnInteger , EmptyPage
from django.views.generic import ListView
from Blog.models import *
from taggit.models import Tag

from Blog.forms import *
# Create your views here.

def index(request,tag_slug=None):
    posts = Post.objects.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = posts.filter(tags__in=[tag])
    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page')
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:    #First page when not passing page number
        posts = paginator.page(1)
    except EmptyPage:   #last page if not found
        posts = paginator.page(paginator.num_pages)
    return render(request , 'Blog/index.html' , {'posts':posts, 'tag':tag})

def post_detail_view(request,year,month,day,post):
    post = get_object_or_404(Post,slug=post,status='published',publish__year=year,
                             publish__month=month,publish__day=day)
    # or 
    # post = Post.objects.get(slug=post,status='published',publish__year=year,
    #                          publish__month=month,publish__day=day)
    
    comments = post.comments.filter(active=True)
    cSubmit = False
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit = False)
            new_comment.post = post
            new_comment.save()
            cSubmit = True
    else:
        form = CommentForm()
    return render(request,'Blog/post_detail.html',{'post':post,'form':form,'comments':comments,'csubmit':cSubmit})

from django.core.mail import send_mail

def MailSendView(request, id):
    post = get_object_or_404(Post, id=id, status='published')
    sent = False
    if request.method == "POST":
        form = EmailSendForm(request.POST)
        if form.is_valid():
            values = form.cleaned_data
            send_mail('Subject', values['comments'], values['name'], [values['to']], fail_silently=False )
            sent = True
    
    else:
        form = EmailSendForm()
    return render(request, 'Blog/sendbymail.html', {'form':form, 'post':post, 'sent':sent})


# Pagination using Class Based Views:
# -----------------------------------
# class Paginator(ListView):
#     posts = Post.objects.all()
#     paginate_by = 1
#     model = Post
#     template_name = 'Blog/index.html'

# NOTE: In Class Based Views if we pass page=1000 i.e not the page number it will give 404 but in this Function Based View it returns last page 

# Sending mail via django:
# ------------------------
# Django provides mail Module and send_mail() function 
# SMTP Server 
# SMTP --> Simple Mail Transfer Protocol 

# EMAIL_HOST = SMTP SERVER HOST default value is localhost don't use : insted of =
# EMAIL_PORT = THE SMTP SERVER PORT default is 25
# EMAIL_HOST_USER = "Your Email UserName"
# EMAIL_HOST_PASSWORD = "Your email PASSWORD"
# EMAIL_USE_TLS = Bool
# TRANSPORT LAYER SECURITY

# For Gmail Account:
# ------------------
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = T587
# EMAIL_HOST_USER = "UserName"
# EMAIL_HOST_PASSWORD = "PASSWORD"
# EMAIL_USE_TLS = True 


# Making Custom Template Tags

# 3 utility functions to define our own custom template tags 

# simple_tag: perform some processing and returns a string 
# inclusion_tag: perform some processing and returns a rendered template includes the rendered template or in other words returns some html code
# assingment_tag: perform some processing and assigns the result to the variable in the context but removed in django2.0 
# simple_tag can be used instead of assingment_tag

# 1. make a folder named as templatetags inside application folder 
# 2. inside templatetags folder make 2 files 1. __init__.py and second any *.py file to store custom template tags 

DjangoBlog/templates/Blog/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

{% load blog_tags %}   <!-- IMPORTANT : loading custom tags not in django documentation -->

    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href={% static "css\bootstrap.min.css" %}>
        <script type="text/javascript" src={% static "js\bootstrap.min.js" %}></script>
        <script src={% static "js\jquery-3.2.1.slim.min.js" %} ></script>
        <script src={% static "js\popper.min.js" %}></script>   
        <link rel="stylesheet" href={% static "css\self.css" %}>
        <title>{% block title %} {% endblock %}</title>
    </head>

    <body>
        <hr class="bg-dark mx-5">
        {% block body %}
        
        {% endblock body %}

    </body>
</html>

DjangoBlog/templates/Blog/index.html
{% extends "Blog/base.html" %}

{% load blog_tags %}   <!-- IMPORTANT : loading custom tags not in django documentation -->

{% block title %} Blog..{% endblock %}

{% block body %}
    <h1 class=" text-center"> Blog Project </h1><hr class="bg-dark mx-5">
    <div class="container-fluid row">
        <div class="container-fluid col-md-7">
            {% if tag %}
                <h2>Posts Related to "{{tag.name}}"</h2>
            {% endif %}
            {% for post in posts %}
                <div class=" ml-3">
                    <a href="{{post.get_absolute_url}}"> <h1> {{post.title}} </h1> </a>
                    <p class="font-italic text-success"> Published on {{post.publish}} by {{post.author|title}} </p>
                    <p class="text-danger font-weight-bold">Tags : 
                        {% for tag in post.tags.all %}
                        <a class="btn btn-warning rounded mr-2 font-weight-bold" href="{% url 'post_list_by_tag_name' tag.slug %}"> {{tag}} </a>
                        {% endfor %}
                    </p>
                    <p> {{ post.body|truncatewords:50}} </p>
                </div>
            {% endfor %}
        </div>
        <div class="container-fluid col-md-5 bg-dark">
            <h1 class="mt-3 text-center text-white">Om Gupta's Blog</h1><hr class="bg-light">
            <p class="text-white text-center">The Total Number of Published Posts Upto Today is : {% total_posts %} </p>
            <p class="text-white">This is a sample blog made with django for learning Django. Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio, cum iure. Recusandae itaque ex, beatae veniam consequatur amet minus placeat?</p>
            <p class="text-white">You will get latest updates about every topic. Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit laborum assumenda pariatur voluptates tempora mollitia asperiores fugiat iusto doloribus consequatur.</p>
            <p class="text-white">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas deserunt dolorum, dolor fugiat culpa iste blanditiis ab quod enim. Suscipit dicta quia soluta voluptatum, cupiditate expedita cum distinctio! Quaerat nemo, a ducimus incidunt illo sequi eaque possimus porro quasi quos!</p>

            <h3 class="text-light" >Latest Post : </h3>
            {% Latest 5 %}

            <h3 class="text-light" >Most Commented Post : </h3>
            {% most_commented 4 as most_commented_posts %}
            <ul>
                {% for post in most_commented_posts %}
                    <li class="text-warning" ><a href="{{ post.get_absolute_url }}" class="text-warning" >{{post.title}}</a></li>
                {% endfor %}
            </ul>
            
        </div>        
    </div>
    {% include "Blog/paginator.html" with page=posts %}
    
{% endblock body %}

DjangoBlog/templates/Blog/latest.html
<ul>
    {% for post in latest %}
        <li class="text-warning" ><a href="{{ post.get_absolute_url }}" class="text-warning" >{{post.title}}</a></li>
    {% endfor %}
</ul>

DjangoBlog/templates/Blog/paginator.html
<div class="container align-content-center paginator">   
    <div class="container row">
        {% if page.has_previous %}
            <a href="?page={{page.previous_page_number}}" class="btn btn-success"> Previous </a>
        {% endif %}
        <h4 class="mx-3 mt-1">Page {{page.number}} of {{page.paginator.num_pages}} </h4>
        {% if page.has_next %}
            <a href="?page={{page.next_page_number}}" class="btn btn-success mb-5"> Next </a>
        {% endif %}
    </div> 
</div>

DjangoBlog/templates/Blog/post_detail.html
{% extends "Blog/base.html" %}

{% block title %} Blog...{% endblock %}

{% block body %}
    <div class="container">
        <h1> {{post.title}} </h1>
        <p class="font-italic text-success"> Published on {{post.publish}} by {{post.author|title}} </p>
        <p> {{post.body|linebreaks}} </p>
        <a href="/{{post.id}}/share" class="btn btn-lg btn-danger"> Share Post by Email </a>

        {% with comments.count as comment_count %}
            <h2 class="mt-3 text-warning">{{comment_count}} Comment{{comment_count|pluralize}}</h2>
        {% endwith %}

        {% if comments %}
            {% for comment in comments %}
                <p class="mb-1 mt-3 text-primary font-weight-bold">Comment {{forloop.counter}} by {{comment.name}} on {{comment.created}}</p>
                <p class="ml-2 text-success font-weight-bold">👍<span class="ml-2 text-success font-italic">{{comment.body}}</span></p>
                <hr class="bg-warning">
            {% endfor %}
        {% else %}
        <p class="ml-2 text-success font-weight-bold">😥<span class="ml-2 text-success font-italic">There are no Comments Yet.. </span></p>
        {% endif %}

        {% if csubmit %}
            <h2 class="text-danger mb-5">👏Your Comment Added Successfully</h2>
        {% else %}
        <h3 class="text-danger font-italic">Add Your Own Comment Here Below.</h3>
            <form method="post">
                {% csrf_token %}
                <div class="container row">
                    <div class="container mt-3 col-md-6">
                        <label for="id_name" class="ml-2 mr-3 text-success font-weight-bold">Name :</label><br>{{form.name}}
                    </div>
                    <div class="container mt-3 col-md-6">
                        <label for="id_email" class="ml-2 text-success font-weight-bold">Email :</label><br>{{form.email}}
                    </div>
                </div>
                <div class="container row">
                    <div class="container col-md-12">
                        <label for="id_body" class="ml-2 mr-3 text-success font-weight-bold align-content-center">Comment :</label><br>
                        {{form.body}}
                    </div>
                    
                </div>
                <button type="submit" class="mr-5 mt-2 mb-5 btn btn-outline-success float-right">Submit Comment </button>            
            </form>
        {% endif %}
    </div> 
    
{% endblock %}

DjangoBlog/templates/Blog/sendbymail.html
{% extends "Blog/base.html" %}

{% block title %}
    Share {{post.title}} by Email..
{% endblock title %}

{% block body %}
    <div class="container">
        {% if sent %}
            <h1>Post {{post.title}} Sent Successfully </h1>
        {% else %}
            <h1>Share {{post.title}} by Email..</h1><hr class=" bg-warning">
            <form method="post">
                <div class="container row mt-3">
                    <div class="container mt-3 col-md-4">
                        <label for="id_name" class="ml-2 width-100 text-success font-weight-bold">Name :</label><br>{{form.name}}
                    </div>
                    <div class="container mt-3 col-md-4">
                        <label for="id_email" class="ml-2 width-100 text-success font-weight-bold">Email :</label><br>{{form.email}}
                    </div>
                    <div class="container mt-3 col-md-4">
                        <label for="id_to" class="ml-2 width-100 text-success font-weight-bold">To:</label><br>{{form.email}}
                    </div>
                </div>
                <div class="container row mt-3">
                    <div class="container col-md-12">
                        <label for="id_body" class="ml-2 mr-3 text-success font-weight-bold align-content-center">Comment :</label><br>
                        {{form.comments}}
                    </div>
                {% csrf_token %}
                <button type="submit" class="mr-5 mt-2 mb-5 ml-auto btn btn-outline-danger rounded">Send..</button>
            </form>
        {% endif %}
    </div>
    
{% endblock body %}